export class CardsService {
    getCards(){
        return[
            {
                imageUrl: "../../assets/img/beach.svg",
                cardName: "Beach",
            },
            {
                imageUrl:"../../assets/img/iceberg.svg",
                cardName:"Iceberg",
            },
            {
                imageUrl:"../../assets/img/mountains.svg",
                cardName:"Mountains",
            },
            {
                imageUrl:"../../assets/img/waterfall.svg",
                cardName:"waterfall",
            },
            {
                imageUrl:"../../assets/img/windmills.svg",
                cardName:"Windmills",
            },
            {
                imageUrl:"../../assets/img/desert.svg",
                cardName:"Dessert",
            },
            {
                imageUrl: "../../assets/img/beach.svg",
                cardName: "Beach",
            },
            {
                imageUrl:"../../assets/img/iceberg.svg",
                cardName:"Iceberg",
            },
            {
                imageUrl:"../../assets/img/mountains.svg",
                cardName:"Mountains",
            },
            {
                imageUrl:"../../assets/img/waterfall.svg",
                cardName:"waterfall",
            },
            {
                imageUrl:"../../assets/img/windmills.svg",
                cardName:"Windmills",
            },
            {
                imageUrl:"../../assets/img/desert.svg",
                cardName:"Dessert",
            },
        ];
    }
    getCardback(){
        return [
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven1",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven2",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven3",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven4",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven5",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven6",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven7",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven8",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven9",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven10",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven11",
            },
            {
                imageUrl:"../../assets/img/seven.svg",
                cardName:"Seven12",
            },
        ];
    }
}